<?php

namespace Entities;

use Doctrine\ORM\EntityRepository;

/**
 * AcessosUsuariosRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AcessosUsuariosRepository extends EntityRepository
{
}
